config/routes.rb
Rails.application.routes.draw do
  resources :books do
    resources :lendings do
      member do
        patch 'borrow'
        patch 'return'
        get 'return' # Add this line to support GET requests for the return action
      end
    end
  end

  resources :borrowers, only: [:index, :show]

  root 'books#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
    has_many :lendings
    has_many :borrowers, through: :lendings
  
    validates :title, presence: true
    validates :author, presence: true
  end
  

app/models/borrower.rb
class Borrower < ApplicationRecord
    has_many :lendings
    has_many :books, through: :lendings
  
    validates :name, presence: true
  end
  

app/models/lending.rb
class Lending < ApplicationRecord
  belongs_to :book
  belongs_to :borrower

  validates :borrowed_on, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all 
  end

  def show
    @book = Book.find(params[:id])
    @lendings = @book.lendings.includes(:borrower)
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to @book
    else 
      render :new
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to @book
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path, notice: 'Book was successfully deleted.'
  end

  private

  def book_params
    params.require(:book).permit(:title, :author, :description)
  end
end

app/controllers/borrowers_controller.rb
class BorrowersController < ApplicationController
  def show
    @borrower = Borrower.find(params[:id])
    @lendings = @borrower.lendings.includes(:book)
  end

  def index
    @borrowers = Borrower.all
  end
end

app/controllers/lendings_controller.rb
class LendingsController < ApplicationController
  def new
    @book = Book.find(params[:book_id])
    @lending = @book.lendings.new
  end

  def create
    @book = Book.find(params[:book_id])
    @borrower = Borrower.find_or_create_by(name: params[:lending][:borrower_name])

    if @borrower.persisted?
      @lending = @book.lendings.new(borrower: @borrower, borrowed_on: Date.today)
      if @lending.save
        redirect_to @book, notice: 'Book borrowed successfully.'
      else
        @lending = @book.lendings.new
        render :new, status: :unprocessable_entity
      end
    else
      @lending = @book.lendings.new
      render :new, alert: 'Unable to create or find borrower.', status: :unprocessable_entity
    end
  end

  def borrow
    @book = Book.find(params[:book_id])
    @borrower = Borrower.find_or_create_by(name: params[:borrower_name])

    if @borrower.persisted?
      @lending = @book.lendings.new(borrower: @borrower, borrowed_on: Date.today)
      if @lending.save
        redirect_to @book, notice: 'Book borrowed successfully.'
      else
        redirect_to @book, alert: 'Unable to borrow book.'
      end
    else
      redirect_to @book, alert: 'Unable to create or find borrower.'
    end
  end

  def return
    @book = Book.find(params[:book_id])
    @lending = @book.lendings.find(params[:id])
    if @lending.update(returned_on: Date.today)
      redirect_to @book, notice: 'Book returned successfully.'
    else
      redirect_to @book, alert: 'Unable to return book.'
    end
  end

  private

  def lending_params
    params.require(:lending).permit(:borrower_name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/borrowers_helper.rb
module BorrowersHelper
end

app/helpers/lendings_helper.rb
module LendingsHelper
end

app/views/books/edit.html.erb
<h1>Edit Book</h1>

<%= form_with model: @book, local: true do |form| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<h1>Books</h1>
<%= link_to 'Add New Book', new_book_path %>
<ul>
  <% @books.each do |book| %>
    <li>
      <%= link_to book.title, book_path(book) %>
      <%= link_to 'Edit', edit_book_path(book) %> |
      <%= link_to 'Delete', book_path(book), method: :delete, data: { confirm: 'Are you sure?' } %> |
      <% lending = book.lendings.find_by(returned_on: nil) %>
      <% if lending %>
        <%= link_to 'Return Book', return_book_lending_path(book, lending), method: :patch, data: { confirm: 'Are you sure you want to return this book?' } %>
      <% else %>
        <%= link_to 'Borrow', new_book_lending_path(book) %>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= form_with model: @book, local: true do |form| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<h1><%= @book.title %></h1>
<p><strong>Author:</strong> <%= @book.author %></p>
<p><strong>Description:</strong> <%= @book.description %></p>

<h2>Borrowing History</h2>
<ul>
  <% @book.lendings.each do |lending| %>
    <li>
      <strong>Borrower:</strong> <%= lending.borrower.name %> |
      <strong>Borrowed On:</strong> <%= lending.borrowed_on %> |
      <strong>Returned On:</strong> <%= lending.returned_on %>
      <% if lending.returned_on.nil? %>
        | <%= link_to 'Return', return_book_lending_path(@book, lending), method: :patch, data: { confirm: 'Are you sure you want to return this book?' } %>
      <% end %>
    </li>
  <% end %>
</ul>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/borrowers/index.html.erb
# filepath: /C:/Users/user/BookLendingLibrary/app/views/borrowers/index.html.erb
<h1>Borrowers</h1>
<ul>
  <% @borrowers.each do |borrower| %>
    <li>
      <%= link_to borrower.name, borrower_path(borrower) %>
    </li>
  <% end %>
</ul>

app/views/borrowers/show.html.erb
<h1>Borrower: <%= @borrower.name %></h1>

<h2>Borrowing History</h2>
<ul>
  <% @borrower.lendings.each do |lending| %>
    <li>
      <strong>Book:</strong> <%= link_to lending.book.title, book_path(lending.book) %> |
      <strong>Borrowed On:</strong> <%= lending.borrowed_on %> |
      <strong>Returned On:</strong> <%= lending.returned_on %>
    </li>
  <% end %>
</ul>

<%= link_to 'Back', books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Book Lending Library" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%= stylesheet_link_tag "application", media: "all", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Book Lending Library</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <%= link_to 'Home', root_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Books', books_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Borrowers', borrowers_path, class: 'nav-link' %>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/lendings/new.html.erb
<h1>Borrow Book: <%= @book.title %></h1>

<%= form_with model: [@book, @lending], url: book_lendings_path(@book), method: :post, local: true do |form| %>
  <div class="field">
    <%= form.label :borrower_name, "Borrower's Name" %>
    <%= form.text_field :borrower_name %>
  </div>

  <div class="actions">
    <%= form.submit "Borrow" %>
  </div>
<% end %>

<%= link_to 'Back', book_path(@book) %>